import React, { useState } from 'react';
import { AIProviderSelector } from '../components/AIProviderSelector';
import { AIChatPanel, ChatMessage } from '../components/AIChatPanel';
import { AIPromptInput } from '../components/AIPromptInput';
import { AIOutputPanel } from '../components/AIOutputPanel';
import { AIGenerationHistory } from '../components/AIGenerationHistory';
import { useAIStore } from '../../../store/ai.store';
import apiClient from '../../../api/client';
import toast from 'react-hot-toast';

export const AIWorkspacePage: React.FC = () => {
  const { activeProvider } = useAIStore();
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [outputContent, setOutputContent] = useState<string>('');
  const [isGenerating, setIsGenerating] = useState(false);

  const handleSendPrompt = async (promptText: string) => {
    const userMsg: ChatMessage = {
      id: `u_${Date.now()}`,
      sender: 'user',
      text: promptText,
      timestamp: new Date().toLocaleTimeString(),
    };
    setMessages((prev) => [...prev, userMsg]);
    setIsGenerating(true);

    try {
      const res = await apiClient.post('/ai/completion', {
        prompt: promptText,
        providerId: activeProvider,
      });

      const completionText = res.data?.data?.text || 'No output generated by AI Engine.';
      const modelUsed = res.data?.data?.model || activeProvider;

      const aiMsg: ChatMessage = {
        id: `a_${Date.now()}`,
        sender: 'ai',
        text: `Response generated using ${activeProvider.toUpperCase()} (${modelUsed}):\n\n${completionText.slice(0, 300)}...`,
        timestamp: new Date().toLocaleTimeString(),
      };

      setMessages((prev) => [...prev, aiMsg]);
      setOutputContent(completionText);
      toast.success(`Generated using ${activeProvider.toUpperCase()}`);
    } catch (err: any) {
      toast.error(err.message || 'AI Completion failed.');
      const errorMsg: ChatMessage = {
        id: `err_${Date.now()}`,
        sender: 'ai',
        text: `Error generating response: ${err.message}`,
        timestamp: new Date().toLocaleTimeString(),
      };
      setMessages((prev) => [...prev, errorMsg]);
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="container-fluid px-0 h-100 d-flex flex-column">
      {/* Top Controls Bar */}
      <div className="d-flex align-items-center justify-content-between p-3 glass-card rounded-4 mb-3">
        <h4 className="fw-bold mb-0 gradient-text">AI Workspace</h4>
        <AIProviderSelector />
      </div>

      {/* Split Screen Grid */}
      <div className="row g-3 flex-grow-1 overflow-hidden">
        {/* Left Column: Chat & Input */}
        <div className="col-lg-7 d-flex flex-column h-100">
          <AIChatPanel messages={messages} />
          <AIPromptInput onSend={handleSendPrompt} isLoading={isGenerating} />
        </div>

        {/* Right Column: Output Panel & History */}
        <div className="col-lg-5 d-flex flex-column gap-3 h-100 overflow-auto">
          <div className="flex-grow-1">
            <AIOutputPanel content={outputContent} model={activeProvider} />
          </div>
          <AIGenerationHistory />
        </div>
      </div>
    </div>
  );
};
