import { PromptCategory, PromptType, TechStackId } from '../types/prompt.types';

export const PROMPT_CATEGORIES: PromptCategory[] = [
  'Frontend',
  'Backend',
  'Mobile',
  'Database',
  'DevOps',
  'Cloud',
  'AI',
  'Security',
  'Testing',
  'Architecture',
  'Microservices',
];

export const PROMPT_TYPES: PromptType[] = [
  'Coding',
  'Architecture',
  'Debugging',
  'Refactoring',
  'Security Review',
  'Code Review',
  'API Development',
  'Database Design',
  'Deployment',
  'SaaS Development',
  'Mobile App',
  'Enterprise System',
];

export const TECH_STACKS: { id: TechStackId; label: string; category: PromptCategory }[] = [
  { id: 'react', label: 'React.js', category: 'Frontend' },
  { id: 'nextjs', label: 'Next.js', category: 'Frontend' },
  { id: 'vue', label: 'Vue.js', category: 'Frontend' },
  { id: 'angular', label: 'Angular', category: 'Frontend' },
  { id: 'typescript', label: 'TypeScript', category: 'Frontend' },
  { id: 'javascript', label: 'JavaScript', category: 'Frontend' },
  { id: 'nodejs', label: 'Node.js', category: 'Backend' },
  { id: 'express', label: 'Express.js', category: 'Backend' },
  { id: 'nestjs', label: 'NestJS', category: 'Backend' },
  { id: 'python', label: 'Python', category: 'Backend' },
  { id: 'django', label: 'Django', category: 'Backend' },
  { id: 'flask', label: 'Flask', category: 'Backend' },
  { id: 'fastapi', label: 'FastAPI', category: 'Backend' },
  { id: 'laravel', label: 'Laravel (PHP)', category: 'Backend' },
  { id: 'springboot', label: 'Spring Boot (Java)', category: 'Backend' },
  { id: 'go', label: 'Go (Golang)', category: 'Backend' },
  { id: 'rust', label: 'Rust', category: 'Backend' },
  { id: 'csharp', label: 'C# / ASP.NET', category: 'Backend' },
  { id: 'ruby-on-rails', label: 'Ruby on Rails', category: 'Backend' },
  { id: 'react-native', label: 'React Native', category: 'Mobile' },
  { id: 'flutter', label: 'Flutter / Dart', category: 'Mobile' },
  { id: 'swift', label: 'Swift (iOS)', category: 'Mobile' },
  { id: 'kotlin', label: 'Kotlin (Android)', category: 'Mobile' },
  { id: 'mongodb', label: 'MongoDB', category: 'Database' },
  { id: 'postgresql', label: 'PostgreSQL', category: 'Database' },
  { id: 'mysql', label: 'MySQL', category: 'Database' },
  { id: 'redis', label: 'Redis', category: 'Database' },
  { id: 'docker', label: 'Docker', category: 'DevOps' },
  { id: 'kubernetes', label: 'Kubernetes', category: 'DevOps' },
  { id: 'cicd', label: 'CI/CD Pipelines', category: 'DevOps' },
  { id: 'aws', label: 'AWS', category: 'Cloud' },
  { id: 'azure', label: 'Microsoft Azure', category: 'Cloud' },
  { id: 'gcp', label: 'Google Cloud (GCP)', category: 'Cloud' },
  { id: 'microservices', label: 'Microservices', category: 'Architecture' },
  { id: 'ai-apps', label: 'AI Applications', category: 'AI' },
];
